Revert "handling of luaposix for dynamic environments"
This reverts commit 8381f1a8cfbf5f23e4d7eb30e0615bc5c9c67316.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"