neutrinoapi.cpp: fix possible broken build
error: ‘to_string’ was not declared...

to_string is handled inside helpers.h/cpp.
include of <system/helpers.h> is required here.